---
- name: Check Server Status
  hosts: servers
  gather_facts: yes
  tasks:
    - name: Check if JBoss is running
      shell: ps aux | grep jboss | grep -v grep
      register: jboss_process
      ignore_errors: yes
      changed_when: false

    - name: Get JBoss version
      shell: find /opt -name 'standalone.sh' -exec dirname {} \; | xargs -I {} find {} -name 'jboss-modules.jar' -exec java -jar {} --version \; 2>/dev/null
      register: jboss_version
      ignore_errors: yes
      changed_when: false

    - name: Check JBoss ports
      shell: netstat -tlnp | grep java | grep -E ':(8080|8443|9990|9999)'
      register: jboss_ports
      ignore_errors: yes
      changed_when: false

    - name: Get JBoss memory usage
      shell: ps aux | grep jboss | grep -v grep | awk '{print $6}' | head -1
      register: jboss_memory
      ignore_errors: yes
      changed_when: false

